version: "2.4"
services:

    reverse-proxy:
        image: "jwilder/nginx-proxy:alpine"
        #image: "jwilder/nginx-proxy:latest"
        #image: "nginx:stable-alpine"
        container_name: "reverse-proxy"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/tmp/docker.sock:ro"
        restart: "unless-stopped"
        networks: 
            - "net"
        ports:
            - "80:80"
            - "443:443"
    letsencrypt:
        image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
        container_name: "letsencrypt-helper"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            NGINX_PROXY_CONTAINER: "reverse-proxy"
            DEFAULT_EMAIL: "admin@sensely.ml"
        restart: "unless-stopped"
        depends_on:
            - "reverse-proxy"
        networks: 
            - "net"


    whoogle:
        image: "benbusby/whoogle-search:latest"
        container_name: "whoogle"
        environment:
            VIRTUAL_HOST: "sensely.ml"
            VIRTUAL_PORT: "80"
            LETSENCRYPT_HOST: "sensely.ml"
        restart: "unless-stopped"
        depends_on:
            - "reverse-proxy"
        networks: 
            - "net"


volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  net:
    external: true
