version: '2.4'

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    logging:
        driver: none
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      - proxy-tier

  app:
    image: nextcloud:fpm-alpine
    restart: unless-stopped
    logging:
        driver: none
    volumes:
      - nextcloud:/var/www/html
      - /root/nxtcld/app/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - /root/nxtcld/app/php.ini-production:/usr/local/etc/php/php.ini-production
      - /root/nxtcld/app/php.ini-development:/usr/local/etc/php/php.ini-development
      - /root/nxtcld/app/php.ini-production:/usr/local/etc/php/php.ini
    environment:
      - POSTGRES_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    networks:
      - proxy-tier

  web:
          #build: ./web
    image: nginx:alpine
    restart: unless-stopped
    logging:
        driver: none
    volumes:
      - /root/nxtcld/web/nginx.conf:/etc/nginx/nginx.conf
      - nextcloud:/var/www/html:ro
    environment:
      VIRTUAL_HOST: "sensely.tk,www.sensely.tk"
      LETSENCRYPT_HOST: "sensely.tk,www.sensely.tk"
      LETSENCRYPT_EMAIL: "admin@sensely.tk"
    depends_on:
      - app
    networks:
      - proxy-tier
        #- default

  proxy:
          #build: ./proxy
    image: jwilder/nginx-proxy:alpine
    restart: unless-stopped
    logging:
        driver: none
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /root/nxtcld/proxy/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
      - certs:/etc/nginx/certs:ro
      - dhparam:/etc/nginx/dhparam
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
      - net
    depends_on:
      - app
      - whoogle

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
      - proxy
    volumes:
      - certs:/etc/nginx/certs
      - dhparam:/etc/nginx/dhparam
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
        #environment:
        #- ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
    networks:
      - proxy-tier
      - net
    depends_on:
      - proxy

  whoogle:
    image: "benbusby/whoogle-search:latest"
    container_name: "whoogle"
    logging:
        driver: none
    volumes:
        - "/root/whoogle/config/languages.json:/usr/src/app/app/misc/languages.json"
        - "/root/whoogle/config/countries.json:/usr/src/app/app/misc/countries.json"
    environment:
        VIRTUAL_HOST: "sensely.ml,www.sensely.ml"
        VIRTUAL_PORT: "80"
        LETSENCRYPT_HOST: "sensely.ml,www.sensely.ml"
        LETSENCRYPT_EMAIL: "admin@sensely.ml"
    restart: "unless-stopped"
    networks:
        - net
          #depends_on:
          #- proxy




volumes:
  db:
  nextcloud:
  certs:
  acme:
  dhparam:
  vhost.d:
  html:

networks:
  proxy-tier:
  net:
